name = "sam-tail-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "sam-tail-worker-staging"

[[env.staging.services]]
binding = "API_WORKER"
service = "sam-api-staging"

[env.production]
name = "sam-tail-worker-prod"

[[env.production.services]]
binding = "API_WORKER"
service = "sam-api-prod"
